config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'charges/import' => 'charges#import'
  post 'charges/import' => 'charges#import'
  get 'charges/process_charge' => 'charges#process_charge'

  resources :charges
  root to: "charges#import"

  get 'reports/:year', 
    to: 'reports#year',
    as: 'report_year'

  get 'reports/:year/category/:category',
    to: 'reports#category_year',
    as: 'report_category_year'

  get 'reports/:year/category/:category/:month',
    to: 'reports#category_month',
    as: 'report_category_month'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/charge.rb
class Charge < ActiveRecord::Base
  paginates_per 50
  belongs_to :category
  scope :unprocessed, -> { where(processed: false) }
  scope :processed, -> { where(processed: true) }
  scope :in_year, -> (year) { where('transaction_date >= ? AND transaction_date < ?', Date.new(year), Date.new(year + 1)) }
  scope :in_month, -> (year, month) { where('transaction_date >= ? AND transaction_date < ?', Date.new(year, month), Date.new(year, month + 1)) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  rescue_from Exception, with: :internal_error


  def internal_error(e)
    puts e.message
    puts e.backtrace
    raise e
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def index
    @charges = Charge.order(transaction_date: :desc).page params[:page]
  end
  def import
    if request.post?
      unless params[:file].present?
        flash[:alert] = 'Please provide a file'
        render :import
        return
      end
      two_digit = params[:two_digit_year].present? && params[:two_digit_year] == 'yes'
      raw_charges = CSV.read(params[:file].path, headers: true)
      ChargeRepository.parse_and_create_charges(raw_charges, two_digit_year: two_digit, importer: params[:imported_by])
      go_to_next_or_home
    end
  end

  def edit
    @charge = Charge.find(params[:id]) 
    @categories = Category.all
  end

  def update
    @charge = Charge.find(params[:id])
    permitted = params.require(:charge).permit(:category_id, :amount).merge(processed: true)
    @charge.update_attributes(permitted)
    go_to_next_or_home
  end

  def destroy
    Charge.destroy(params[:id])
    go_to_next_or_home
  end

  private

  def go_to_next_or_home
    nxt = ChargeRepository.next_unprocessed_charge
    if nxt
      redirect_to edit_charge_path(nxt)
    else
      redirect_to report_year_path(year: Date.today.year)
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def year
    @year = params[:year]
    charges = Charge.processed.includes(:category).in_year(@year.to_i)
    @charge_sets = []
    Category.all.map do |category|
      @charge_sets << ChargeSet.new(category: category, charges: charges.where(category: category))
    end

    @total_spent = @charge_sets.inject(0) { |m,s| m += s.spent }
    @total_budgeted = @charge_sets.inject(0) { |m,s| m += s.budgeted } 
  end

  def category_year
    @category = Category.find_by(name: params[:category])
    @year = params[:year]
    @charges = Charge.processed.in_year(@year.to_i).where(category: @category).order(transaction_date: :desc)
    @charge_set = ChargeSet.new(charges: @charges, category: @category)
    @months = @charge_set.months
  end

  def category_month
    @category = Category.find_by(name: params[:category])
    @year = params[:year].to_i
    @month = params[:month].to_i
    @month_name = Date.new(@year, @month).strftime("%B")
    @charges = Charge.processed.in_month(@year, @month).where(category: @category).order(transaction_date: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_charge_table.html.erb
<table class="table table-striped">
  <thead>
    <th>Date</th>
    <th>Amount</th>
    <th>Category</th>
  </thead>
  <tbody>
    <% charges.each do |charge| %>
      <tr>
        <td><%= charge.transaction_date %></td>
        <td><%= number_to_currency(charge.amount) %></td>
        <td><%= charge.category.try(:name) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/application/_nav.html.erb
<div class="nav-container_outer">
  <%= link_to '', report_year_path(year: Date.today.year), class: 'navbar-brand' %>
  <div class="container">
    <nav class="header navbar navbar-light">
      <ul class="nav navbar-nav">
        <li class="nav-item">
          <%= link_to 'Import Charges', charges_import_path %>
        </li>
        <% if Charge.unprocessed.count > 0 %>
          <li class="nav-item">
            <%= link_to 'Process Charges', edit_charge_path(Charge.unprocessed.first) %> 
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to 'Reports', report_year_path(year: Date.today.year) %>
        </li>
        <li class="nav-item">
          <%= link_to 'Admin', new_admin_user_session_path %>
        </li>
      </ul>
    </nav>
  </div>
</div>

app/views/charges/edit.html.erb
<%= semantic_form_for @charge do |f| %>
  <h1><%= @charge.description %></h1>
  <h2><%= @charge.transaction_date %></h2>
  <%= f.input :amount, label: 'Amount $' %>
  <div class="form-group category-choice">
    <%= f.input :category, as: :radio, label: false, collection: @categories.pluck(:name, :id) %> 
  </div>
  <%= f.actions do %>
    <%= f.action :submit, as: :button, button_html: {class: 'btn btn-primary'} %>
  <% end %>
  <%= link_to 'Skip', charge_path(@charge), class: 'btn btn-secondary skip-charge', method: :delete %>
<% end %>

app/views/charges/import.html.erb
<h1>Import New Charges</h1>
  <%= form_tag({action: :import}, multipart: true) do %>
    <div class="form-group">
      <%= label_tag "imported_by", "Who's Importing?" %>
      <%= select_tag "imported_by", options_for_select(["Erin", "Ryan"]) %>
    </div>
    <div class="form-group">
      <%= label_tag 'two_digit_year', 'Two Digit Year?' %>
      <%= check_box_tag :two_digit_year, 'yes', false %>
    </div>
    <div class="form-group">
      <%= file_field_tag :file %>
    </div>
    <%= submit_tag 'Import', class: 'd-block btn btn-primary charges-import' %>
  <% end %>

app/views/charges/index.html.erb
<h1>Charges</h1>
<%= render partial: 'charge_table', locals: {charges: @charges} %>
<%= paginate @charges %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BudgetImporter</title>
  <link href="https://fonts.googleapis.com/css?family=Nunito+Sans" rel="stylesheet">
  <script src="https://npmcdn.com/tether@1.2.4/dist/js/tether.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: 'nav' %>
  <div class="container">
    <% if notice.present? %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/reports/category_month.html.erb
<h1>
  <%= link_to(@year, report_year_path(year: @year)) %> >
  <%= link_to @category.name, report_category_year_path(year: @year, category: @category.name) %> >
  <%= @month_name %>
</h1>
<table class="table table-striped">
  <thead>
    <th>Date</th>
    <th>Description</th>
    <th>Amount</th>
  </thead>
  <tbody>
    <% @charges.each do |charge| %>
      <tr>
        <td><%= charge.transaction_date %></td>
        <td><%= charge.description %></td>
        <td><%= number_to_currency charge.amount %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reports/category_year.html.erb
<h1>
  <%= link_to(@year, report_year_path(year: @year)) %> > 
  <%= @category.name %>
</h1>
<table class="table table-striped">
  <thead>
    <th>Month</th>
    <th>Spent</th>
    <th>Budgeted</th>
    <th>Difference</th>
  </thead>
  <tbody>
    <% @months.keys.each do |month| %>
      <tr>
        <td><%= link_to month, report_category_month_path(year: @year, category: @category.name, month: @months[month][:index]) %></td>
        <td><%= number_to_currency(@months[month][:spent]) %></td>
        <td><%= number_to_currency(@category.limit) %></td>
        <td><%= number_to_currency(@category.limit - @months[month][:spent]) %></td>
      </tr>
    <% end %>
    <tr class="total-row">
      <td>Total</td>
      <td><%= number_to_currency @charge_set.spent %></td>
      <td><%= number_to_currency @charge_set.budgeted %></td>
      <td><%= number_to_currency(@charge_set.budgeted - @charge_set.spent) %></td>
    </tr>
  </tbody>
</table>

app/views/reports/year.html.erb
<h1><%= @year %></h1>
<table class="table table-striped">
  <thead>
    <th>Category</th>
    <th>Spent</th>
    <th>Budgeted</th>
    <th>Difference</th>
  </thead>
  <tbody>
    <% @charge_sets.each do |set| %>
      <tr>
        <td><%= link_to set.category_name, report_category_year_path(year: @year, category: set.category_name) %></td>
        <td><%= number_to_currency(set.spent) %></td>
        <td><%= number_to_currency set.budgeted %></td>
        <td class="<%= 'alert-danger' if set.over_budget? %>"><%= number_to_currency set.difference %></td>
      </tr>
    <% end %>
    <tr class="total-row">
      <td>Total</td>
      <td><%= number_to_currency @total_spent %></td>
      <td><%= number_to_currency @total_budgeted %></td>
      <td><%= number_to_currency(@total_budgeted - @total_spent) %></td>
    </tr>
  </tbody>
</table>

<ul class="charges-years">
  <li><%= link_to '2016', report_year_path(year: 2016) %></li>
</ul>